spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      uri: http://localhost:8888

info:
  component: Product Service
server:
  port: 9788
logging:
  level:
    root:
    com.pblgllgs: DEBUG

---

spring:
  profiles: localhost
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: password
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---

spring:
  profiles: stage
  cloud:
    config:
      uri: http://config-server:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres_db:5432/stock_management"
    username: postgres
    password: password
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka